par(mfrow=c(2,2))
plot(as.numeric(read_file1$Global_active_power),type="l",xlab="",xaxt="n",ylab="Global Active Power")
axis(1,at=c(0,1500,2800), labels = c("Thu","Fri","Sat"))
plot(as.numeric(read_file1$Voltage),ylab="Voltage",xlab="datetime",xaxt="n",type="l")
axis(1,at=c(0,1500,2800),labels=c("Thu","Fri","Sat"))
plot(as.numeric(read_file1$Sub_metering_1),type="l",xlab="", ylab="Energy sub metering", col="green", xaxt="n")
axis(1,at=c(0,1500,2800),labels=c("Thu","Fri","Sat"))
lines(as.numeric(read_file1$Sub_metering_2),type="l",col="orange")
lines(read_file1$Sub_metering_3,type="l",col="blue")
legend("topright",lty = 1,legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("green","orange","blue"),cex=0.2)
plot(as.numeric(read_file1$Global_active_power),ylab="Global_reactive_power",xlab="datetime",xaxt="n",type="l")
axis(1,at=c(0,1500,2800),labels=c("Thu","Fri","Sat"))